#include "a2l_generator.h"
#include <stdio.h>

void generate_a2l(const char* filename, const char* ecuName, const Variable* vars, int varCount) {
    FILE* file = fopen(filename, "w");
    if (!file) {
        printf("❌ Failed to open %s for writing\n", filename);
        return;
    }

    // ASAP2 version
    fprintf(file, "ASAP2_VERSION 1 71\n\n");

    // Project and header
    fprintf(file, "/begin PROJECT %s \"Demo ECU\"\n", ecuName);
    fprintf(file, "  /begin HEADER \"Generated by sample_c_demo\"\n");
    fprintf(file, "  /end HEADER\n\n");

    // Module
    fprintf(file, "  /begin MODULE %s_module \"Demo Module\"\n", ecuName);

    // Each measurement block
    for (int i = 0; i < varCount; i++) {
        fprintf(file,
            "    /begin MEASUREMENT %s \"%s variable\" %s NO_COMPU_METHOD 1 0 %g %g\n"
            "    /end MEASUREMENT\n",
            vars[i].name,       // symbol name
            vars[i].name,       // long identifier
            vars[i].datatype,   // e.g., UWORD, UBYTE, SWORD
            vars[i].minVal,     // lower limit
            vars[i].maxVal      // upper limit
        );
    }

    // End module & project
    fprintf(file, "  /end MODULE\n");
    fprintf(file, "/end PROJECT\n");

    fclose(file);
    printf("✅ Generated A2L file: %s\n", filename);
}
